// Code generated by goctl. DO NOT EDIT!
// Source: gozerorpcdemo.proto

package server

import (
	"context"

	"github.com/1005281342/gozerorpcdemo/gozerorpcdemo"
	"github.com/1005281342/gozerorpcdemo/internal/logic"
	"github.com/1005281342/gozerorpcdemo/internal/svc"
)

type GozerorpcdemoServer struct {
	svcCtx *svc.ServiceContext
}

func NewGozerorpcdemoServer(svcCtx *svc.ServiceContext) *GozerorpcdemoServer {
	return &GozerorpcdemoServer{
		svcCtx: svcCtx,
	}
}

func (s *GozerorpcdemoServer) Ping(ctx context.Context, in *gozerorpcdemo.Request) (*gozerorpcdemo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
